// Autogenerated file
// KAT:
// Poseidon([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]) =
// [0x0f918939632fadca6456a2fe6e65a124828d4c3920d379cc744e90a666887806,
// 0x03c79ae129bdb21fa71f5499dbf1e9682e682c87c34ef409bcb3c0ab6dddc42e,
// 0x0cf39e7b6374fb244025b80a9d269ebd0a0c416f1a7b88e3a784eda197040b74,
// 0x183b8b2a3f080073a01b40e0d1b53d05f7a9b1ad8a609719ab04488177eb17fb,
// 0x06d9fa7c81137a0eb57b1e6940501568ccc685f51368b6853dbdb76f668ded15,
// 0x02d631f83a32055f4fd53391b2455bded041b6dacf7016179195d0818cdb41d6,
// 0x2eb415e6d663f16ac78564455c2174a93ab610514aebf334a6c3c62dc1854288,
// 0x201b92cde94b1dd79b58602bf98fab67a52b60b72b08438d293b657f36c05274,
// 0x0b29ba584936c627c93d48e419c3f3a8d9943a2bbb4f62f1bae8a3b8413e3b82,
// 0x1640bda5e105d1b5522bce8a1201ff947eede90fdabe6326845042fa7deccaaa,
// 0x1f25f09ff350bb118b218b0947114e8dfc41183c7dc054c406d0e7e71d3c4b08,
// 0x04b103f34efdf4947ef4674120423bd114629e14f21f9cf6be30e6c34b6f71a2,
// 0x248a1b69b9479e27f5121cbd7210d1be67a9b3b67020f34ed9c2cd4b92c3e1ab,
// 0x05a2ad96bd0cec0ed170ae830c1800d3e83a72d3fb84673213aab431fc578cb7]; Autogenerated file - Binary
// Backed
use std::sync::{Arc, OnceLock};

use ark_serialize::CanonicalDeserialize;

use crate::parameters::PoseidonParams;

type Scalar = ark_bn254::Fr;

static MDS_BIN: &[u8] = include_bytes!("params/mds_t14.bin");
static RC_BIN: &[u8] = include_bytes!("params/rc_t14.bin");

pub static POSEIDON_CIRCOM_BN_14_PARAMS: OnceLock<Arc<PoseidonParams<Scalar>>> = OnceLock::new();

pub fn get_t14_params() -> Arc<PoseidonParams<Scalar>> {
    POSEIDON_CIRCOM_BN_14_PARAMS
        .get_or_init(|| {
            let mds = MDS_BIN
                .chunks_exact(32)
                .map(|c| Scalar::deserialize_compressed(c).unwrap())
                .collect::<Vec<_>>()
                .chunks(14)
                .map(|c| c.to_vec())
                .collect();

            let rc = RC_BIN
                .chunks_exact(32)
                .map(|c| Scalar::deserialize_compressed(c).unwrap())
                .collect::<Vec<_>>()
                .chunks(14)
                .map(|c| c.to_vec())
                .collect();

            Arc::new(PoseidonParams::new(14, 5, 8, 70, mds, rc).unwrap())
        })
        .clone()
}
