// Autogenerated file
// KAT:
// Poseidon([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]) =
// [0x07e5b070aa2dba008f30a6b785b6c5ae2429e211f71cacdbdae0e07fc05b47a8,
// 0x2c36e7328f048c2ba25f79fcfafacc769122f2dde41a818b11241d17ae867707,
// 0x016f55aae328c5b04cc62b781df8419375d1d7df12df6bfb4b86b6060442695c,
// 0x05d3cebacb3945fbc76165b2276d1e4d0aacabca36c8a50bc4214d30efb26a3d,
// 0x0d20bf02f4fbea024bf6d32e25afc15cc7dbda6325274037d719d77d93ae5c8d,
// 0x069c738536077c296d11592c86f9dd891cfa968f696cd27d6e15d9829997c5a3,
// 0x2e269dd408c488a724c1ff7437f7bf32dd694225f6d4433effb63352d4eb80bf,
// 0x2bd25629cc03fcfda9887ac607a1549511209a3ccf032bc4cd752d80feec95d4,
// 0x245e5169cc6cca781b75854e94b2ee179cd62b5e6221b557fdb7cbe11bc7cd09,
// 0x05037d55a0b53cea251b26bf61b745d1cf3312332d3c99263dd4b4f544dcc6f2,
// 0x0bce3d39a2b8601c6ef886ee266c1b0ff95b2a59334c30890164d7e1e03334c4,
// 0x1941a33364c6d1904c0e540b5170c73567d31cb038d5d6b83cd769412139321a];
// Autogenerated file - Binary Backed
use std::sync::{Arc, OnceLock};

use ark_serialize::CanonicalDeserialize;

use crate::parameters::PoseidonParams;

type Scalar = ark_bn254::Fr;

static MDS_BIN: &[u8] = include_bytes!("params/mds_t12.bin");
static RC_BIN: &[u8] = include_bytes!("params/rc_t12.bin");

pub static POSEIDON_CIRCOM_BN_12_PARAMS: OnceLock<Arc<PoseidonParams<Scalar>>> = OnceLock::new();

pub fn get_t12_params() -> Arc<PoseidonParams<Scalar>> {
    POSEIDON_CIRCOM_BN_12_PARAMS
        .get_or_init(|| {
            let mds = MDS_BIN
                .chunks_exact(32)
                .map(|c| Scalar::deserialize_compressed(c).unwrap())
                .collect::<Vec<_>>()
                .chunks(12)
                .map(|c| c.to_vec())
                .collect();

            let rc = RC_BIN
                .chunks_exact(32)
                .map(|c| Scalar::deserialize_compressed(c).unwrap())
                .collect::<Vec<_>>()
                .chunks(12)
                .map(|c| c.to_vec())
                .collect();

            Arc::new(PoseidonParams::new(12, 5, 8, 60, mds, rc).unwrap())
        })
        .clone()
}
