// Autogenerated file
// KAT:
// Poseidon([0, 1]) = [0x29176100eaa962bdc1fe6c654d6a3c130e96a4d1168b33848b897dc502820133,
// 0x112a4f9241e384b0ede4655e6d2bbf7ebd9595775de9e7536df87cd487852fc4]; Autogenerated file - Binary
// Backed
use std::sync::{Arc, OnceLock};

use ark_serialize::CanonicalDeserialize;

use crate::parameters::PoseidonParams;

type Scalar = ark_bn254::Fr;

static MDS_BIN: &[u8] = include_bytes!("params/mds_t2.bin");
static RC_BIN: &[u8] = include_bytes!("params/rc_t2.bin");

pub static POSEIDON_CIRCOM_BN_2_PARAMS: OnceLock<Arc<PoseidonParams<Scalar>>> = OnceLock::new();

pub fn get_t2_params() -> Arc<PoseidonParams<Scalar>> {
    POSEIDON_CIRCOM_BN_2_PARAMS
        .get_or_init(|| {
            let mds = MDS_BIN
                .chunks_exact(32)
                .map(|c| Scalar::deserialize_compressed(c).unwrap())
                .collect::<Vec<_>>()
                .chunks(2)
                .map(|c| c.to_vec())
                .collect();

            let rc = RC_BIN
                .chunks_exact(32)
                .map(|c| Scalar::deserialize_compressed(c).unwrap())
                .collect::<Vec<_>>()
                .chunks(2)
                .map(|c| c.to_vec())
                .collect();

            Arc::new(PoseidonParams::new(2, 5, 8, 56, mds, rc).unwrap())
        })
        .clone()
}
