// Autogenerated file
// KAT:
// Poseidon([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) =
// [0x0816126a09c29ecfcc0628461dacfb9459816fc60d6738b78db9ad07206fdc21,
// 0x2df759972954f5f7bbc5eaca9f37863f02b9cfe8aa1f737239269245b24bc9e1,
// 0x08d3bedc73ce1876e0a8803479ae33804aed49ef86208a3806171127850a3fc2,
// 0x111fc8aead98723cc59fb9c8109437490c243d84fbf86eeb8f3cc833cb8c3df1,
// 0x14422c2ebd8f3f45e1c862826eeb32adc72d90feef6ac0ed343f3c4a0e1d7ee3,
// 0x1589ffc106576600dc75052a569d2e4a6045888c4825e629006fd439f1d04afa,
// 0x2204d454890737839bee92258b405b2f2de84f1e9e19676078751aaf2ab19789,
// 0x14cc039c591800c5ef17e4cea1c31ad4c74bd2adcdd0160c684e71baafc5cb00,
// 0x07e7acfdc97187aa43e9e790bc98a4e3ec60f016490eff3ddeb904ebc5c370e7,
// 0x237a8b3e5364e33c14f229411fca383580e2f80be5e7d81a28dacc1fa44970ab,
// 0x10f779eb86c66f6e316473976ca0b6b81e8c0c2cadf917ce84bf9cce1b72c45e]; Autogenerated file - Binary
// Backed
use std::sync::{Arc, OnceLock};

use ark_serialize::CanonicalDeserialize;

use crate::parameters::PoseidonParams;

type Scalar = ark_bn254::Fr;

static MDS_BIN: &[u8] = include_bytes!("params/mds_t11.bin");
static RC_BIN: &[u8] = include_bytes!("params/rc_t11.bin");

pub static POSEIDON_CIRCOM_BN_11_PARAMS: OnceLock<Arc<PoseidonParams<Scalar>>> = OnceLock::new();

pub fn get_t11_params() -> Arc<PoseidonParams<Scalar>> {
    POSEIDON_CIRCOM_BN_11_PARAMS
        .get_or_init(|| {
            let mds = MDS_BIN
                .chunks_exact(32)
                .map(|c| Scalar::deserialize_compressed(c).unwrap())
                .collect::<Vec<_>>()
                .chunks(11)
                .map(|c| c.to_vec())
                .collect();

            let rc = RC_BIN
                .chunks_exact(32)
                .map(|c| Scalar::deserialize_compressed(c).unwrap())
                .collect::<Vec<_>>()
                .chunks(11)
                .map(|c| c.to_vec())
                .collect();

            Arc::new(PoseidonParams::new(11, 5, 8, 66, mds, rc).unwrap())
        })
        .clone()
}
