// Autogenerated file
// KAT:
// Poseidon([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) =
// [0x1e0b893aa2ad802275e749d260330b7675b22bb3aaa4461d204af32e60cd9078,
// 0x185d17fe3894188ee3d232d1438b1c2de21acebeddea3adfc99cc7f53b62464e,
// 0x14792dcdbbfb71441ab63103421dcee5ca3c3ddeb94783ce05c1e235e32e7d40,
// 0x1ed2e0e5c9a521f95690b9738193edb887ba1c8af233c7f93bc7266fba058ccc,
// 0x121d84efd03d10a541bfbf728e01e4ef74016e5e4d43ba07f212b8744bbdd54f,
// 0x2ef5de4f77fd3e66ab27d22c682ff741432e52d70cd6c57f424d51140fd8a10b,
// 0x15b7f0167f354415af4af30e2b4b38e177bd1923471a734fc87b6e20a1775518,
// 0x14ec081dd1ff0c970ad8b6338fd41d59bde89699b56d3f69af63f960f50c68dd,
// 0x2a4715ac6731404252e8e6b21aadaf3defd7bdbe3bf8f61da8551551163c2a1a,
// 0x0315afa225921ebb807ba0f33feef2bb5b74c51b740b58faa205dc127e8aa7ac]; Autogenerated file - Binary
// Backed
use std::sync::{Arc, OnceLock};

use ark_serialize::CanonicalDeserialize;

use crate::parameters::PoseidonParams;

type Scalar = ark_bn254::Fr;

static MDS_BIN: &[u8] = include_bytes!("params/mds_t10.bin");
static RC_BIN: &[u8] = include_bytes!("params/rc_t10.bin");

pub static POSEIDON_CIRCOM_BN_10_PARAMS: OnceLock<Arc<PoseidonParams<Scalar>>> = OnceLock::new();

pub fn get_t10_params() -> Arc<PoseidonParams<Scalar>> {
    POSEIDON_CIRCOM_BN_10_PARAMS
        .get_or_init(|| {
            let mds = MDS_BIN
                .chunks_exact(32)
                .map(|c| Scalar::deserialize_compressed(c).unwrap())
                .collect::<Vec<_>>()
                .chunks(10)
                .map(|c| c.to_vec())
                .collect();

            let rc = RC_BIN
                .chunks_exact(32)
                .map(|c| Scalar::deserialize_compressed(c).unwrap())
                .collect::<Vec<_>>()
                .chunks(10)
                .map(|c| c.to_vec())
                .collect();

            Arc::new(PoseidonParams::new(10, 5, 8, 60, mds, rc).unwrap())
        })
        .clone()
}
