// Autogenerated file
// KAT:
// Poseidon([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]) =
// [0x058814945232937db248a01e7cc55b3d681cc08702c8168494e856c1ef7693b5,
// 0x15ebbcb5a7b5633fc41e44ad68f6ff71db704f90e90475d0323f7f31ae372a8a,
// 0x18322ee21c6c451d7ba0c6016962b39a58c2e360c29fa202d093156ff0bbcda4,
// 0x26af967f8e94fab0f0979b103bc07dda7476facd00bcdb1911a6386b4072e6f6,
// 0x1d0d26b886f6408b2fab0106aa9b23ea53f7071ddd135a6b71e51c2166558516,
// 0x0ea889f5588f04eff2026325d9e4808330440a620a5f6121b12d6d980bbed9b8,
// 0x10ab08b962a60a2af872a0380ca8bfe8f29bc5d43634e6f3cedce56a4940a892,
// 0x0f81b92afcfc2c28579f471ed063d98de7189f94847bcccab01904ed7fafd313,
// 0x014035e355d460c3945e5515276692ccbadb6accc02410eb362c52edafd594e4,
// 0x21e817f8920b070e7f536e0855731ada6d31c029f51a9eea4ebac58abcf92769,
// 0x154c981d4646eba83e0eb99f490ce733fdf5527e04fbf07fccfd80e57defb7c8,
// 0x1c5762d6835ec79f8aab00fed30536ab4cb50727a5ce4b710d7804b8fbcaedd7,
// 0x1a6df4eadbafbed2a14f78606ca1326f4bef58a348cffc2a0e8c050dab9cff94]; Autogenerated file - Binary
// Backed
use std::sync::{Arc, OnceLock};

use ark_serialize::CanonicalDeserialize;

use crate::parameters::PoseidonParams;

type Scalar = ark_bn254::Fr;

static MDS_BIN: &[u8] = include_bytes!("params/mds_t13.bin");
static RC_BIN: &[u8] = include_bytes!("params/rc_t13.bin");

pub static POSEIDON_CIRCOM_BN_13_PARAMS: OnceLock<Arc<PoseidonParams<Scalar>>> = OnceLock::new();

pub fn get_t13_params() -> Arc<PoseidonParams<Scalar>> {
    POSEIDON_CIRCOM_BN_13_PARAMS
        .get_or_init(|| {
            let mds = MDS_BIN
                .chunks_exact(32)
                .map(|c| Scalar::deserialize_compressed(c).unwrap())
                .collect::<Vec<_>>()
                .chunks(13)
                .map(|c| c.to_vec())
                .collect();

            let rc = RC_BIN
                .chunks_exact(32)
                .map(|c| Scalar::deserialize_compressed(c).unwrap())
                .collect::<Vec<_>>()
                .chunks(13)
                .map(|c| c.to_vec())
                .collect();

            Arc::new(PoseidonParams::new(13, 5, 8, 65, mds, rc).unwrap())
        })
        .clone()
}
