// Autogenerated file
// KAT:
// Poseidon([0, 1, 2, 3, 4]) = [0x299c867db6c1fdd79dcefa40e4510b9837e60ebb1ce0663dbaa525df65250465,
// 0x1148aaef609aa338b27dafd89bb98862d8bb2b429aceac47d86206154ffe053d,
// 0x24febb87fed7462e23f6665ff9a0111f4044c38ee1672c1ac6b0637d34f24907,
// 0x0eb08f6d809668a981c186beaf6110060707059576406b248e5d9cf6e78b3d3e,
// 0x07748bc6877c9b82c8b98666ee9d0626ec7f5be4205f79ee8528ef1c4a376fc7]; Autogenerated file - Binary
// Backed
use std::sync::{Arc, OnceLock};

use ark_serialize::CanonicalDeserialize;

use crate::parameters::PoseidonParams;

type Scalar = ark_bn254::Fr;

static MDS_BIN: &[u8] = include_bytes!("params/mds_t5.bin");
static RC_BIN: &[u8] = include_bytes!("params/rc_t5.bin");

pub static POSEIDON_CIRCOM_BN_5_PARAMS: OnceLock<Arc<PoseidonParams<Scalar>>> = OnceLock::new();

pub fn get_t5_params() -> Arc<PoseidonParams<Scalar>> {
    POSEIDON_CIRCOM_BN_5_PARAMS
        .get_or_init(|| {
            let mds = MDS_BIN
                .chunks_exact(32)
                .map(|c| Scalar::deserialize_compressed(c).unwrap())
                .collect::<Vec<_>>()
                .chunks(5)
                .map(|c| c.to_vec())
                .collect();

            let rc = RC_BIN
                .chunks_exact(32)
                .map(|c| Scalar::deserialize_compressed(c).unwrap())
                .collect::<Vec<_>>()
                .chunks(5)
                .map(|c| c.to_vec())
                .collect();

            Arc::new(PoseidonParams::new(5, 5, 8, 60, mds, rc).unwrap())
        })
        .clone()
}
