// Autogenerated file
// KAT:
// Poseidon([0, 1, 2, 3, 4, 5]) =
// [0x0dab9449e4a1398a15224c0b15a49d598b2174d305a316c918125f8feeb123c0,
// 0x05cf88c465d1f87a273fed9f778b64367d3b32e45f274c03b4f441940f6d2db9,
// 0x2c6c70449c91e046669977a3bf21021976db909b35843833babfbcba4937a2b3,
// 0x2cabceb63c5f917cc45d3fcbad6733b8d42e2a2a12e1aeb4e3eb8fb6f3d2ca40,
// 0x21ea1279294dbc9a32bc13827d052ce939d5397b4cb7b19e2ead087f41cfdfd7,
// 0x208adf8d7f4ac061f00db710aef42f3b2f13176de26674b0a5f4436b883db6bc]; Autogenerated file - Binary
// Backed
use std::sync::{Arc, OnceLock};

use ark_serialize::CanonicalDeserialize;

use crate::parameters::PoseidonParams;

type Scalar = ark_bn254::Fr;

static MDS_BIN: &[u8] = include_bytes!("params/mds_t6.bin");
static RC_BIN: &[u8] = include_bytes!("params/rc_t6.bin");

pub static POSEIDON_CIRCOM_BN_6_PARAMS: OnceLock<Arc<PoseidonParams<Scalar>>> = OnceLock::new();

pub fn get_t6_params() -> Arc<PoseidonParams<Scalar>> {
    POSEIDON_CIRCOM_BN_6_PARAMS
        .get_or_init(|| {
            let mds = MDS_BIN
                .chunks_exact(32)
                .map(|c| Scalar::deserialize_compressed(c).unwrap())
                .collect::<Vec<_>>()
                .chunks(6)
                .map(|c| c.to_vec())
                .collect();

            let rc = RC_BIN
                .chunks_exact(32)
                .map(|c| Scalar::deserialize_compressed(c).unwrap())
                .collect::<Vec<_>>()
                .chunks(6)
                .map(|c| c.to_vec())
                .collect();

            Arc::new(PoseidonParams::new(6, 5, 8, 60, mds, rc).unwrap())
        })
        .clone()
}
