// Autogenerated file
// KAT:
// Poseidon([0, 1, 2, 3, 4, 5, 6, 7, 8]) =
// [0x2921ab9bd0140cbc98e40395c0fefb40337a4d54fbbecd9a4d43b3d8d0c4d8d1,
// 0x0f4bef710c430ccf4b066245ebda76ec4c571816b5766bffbe64dfcef83ad9ee,
// 0x29ae93298f7f5ac359eed2a1b4fe0b8605e6caf86a2952ddc353edee612f431b,
// 0x0100596375fcd85a397fabfef5af0a64caac9fa4206e3825651c96c00221ad89,
// 0x0f007579146e6d18785d8edd07bfc2ff49ff194bb40da0bfad0fd77239d41104,
// 0x21b31b3be4a08e10a24e2d327ea64077fb18dc9428fa04e30faf543a5cad6c41,
// 0x032589fca1f1eb8f5c617c7256ae25221ed6cb7272b9ce1ff0f4cfb89050e601,
// 0x1e51f0950c8b317a62bb43b082347bdb2b83deb856dabc1cdbbb7569c0e81955,
// 0x2c8e23a3569963447e55619f1d1462f63ea2e40d3d405c18bbf394f13c253749]; Autogenerated file - Binary
// Backed
use std::sync::{Arc, OnceLock};

use ark_serialize::CanonicalDeserialize;

use crate::parameters::PoseidonParams;

type Scalar = ark_bn254::Fr;

static MDS_BIN: &[u8] = include_bytes!("params/mds_t9.bin");
static RC_BIN: &[u8] = include_bytes!("params/rc_t9.bin");

pub static POSEIDON_CIRCOM_BN_9_PARAMS: OnceLock<Arc<PoseidonParams<Scalar>>> = OnceLock::new();

pub fn get_t9_params() -> Arc<PoseidonParams<Scalar>> {
    POSEIDON_CIRCOM_BN_9_PARAMS
        .get_or_init(|| {
            let mds = MDS_BIN
                .chunks_exact(32)
                .map(|c| Scalar::deserialize_compressed(c).unwrap())
                .collect::<Vec<_>>()
                .chunks(9)
                .map(|c| c.to_vec())
                .collect();

            let rc = RC_BIN
                .chunks_exact(32)
                .map(|c| Scalar::deserialize_compressed(c).unwrap())
                .collect::<Vec<_>>()
                .chunks(9)
                .map(|c| c.to_vec())
                .collect();

            Arc::new(PoseidonParams::new(9, 5, 8, 63, mds, rc).unwrap())
        })
        .clone()
}
