// Autogenerated file
// KAT:
// Poseidon([0, 1, 2]) = [0x115cc0f5e7d690413df64c6b9662e9cf2a3617f2743245519e19607a4417189a,
// 0x0fca49b798923ab0239de1c9e7a4a9a2210312b6a2f616d18b5a87f9b628ae29,
// 0x0e7ae82e40091e63cbd4f16a6d16310b3729d4b6e138fcf54110e2867045a30c]; Autogenerated file - Binary
// Backed
use std::sync::{Arc, OnceLock};

use ark_serialize::CanonicalDeserialize;

use crate::parameters::PoseidonParams;

type Scalar = ark_bn254::Fr;

static MDS_BIN: &[u8] = include_bytes!("params/mds_t3.bin");
static RC_BIN: &[u8] = include_bytes!("params/rc_t3.bin");

pub static POSEIDON_CIRCOM_BN_3_PARAMS: OnceLock<Arc<PoseidonParams<Scalar>>> = OnceLock::new();

pub fn get_t3_params() -> Arc<PoseidonParams<Scalar>> {
    POSEIDON_CIRCOM_BN_3_PARAMS
        .get_or_init(|| {
            let mds = MDS_BIN
                .chunks_exact(32)
                .map(|c| Scalar::deserialize_compressed(c).unwrap())
                .collect::<Vec<_>>()
                .chunks(3)
                .map(|c| c.to_vec())
                .collect();

            let rc = RC_BIN
                .chunks_exact(32)
                .map(|c| Scalar::deserialize_compressed(c).unwrap())
                .collect::<Vec<_>>()
                .chunks(3)
                .map(|c| c.to_vec())
                .collect();

            Arc::new(PoseidonParams::new(3, 5, 8, 57, mds, rc).unwrap())
        })
        .clone()
}
