// Autogenerated file
// KAT:
// Poseidon([0, 1, 2, 3]) = [0x0e7732d89e6939c0ff03d5e58dab6302f3230e269dc5b968f725df34ab36d732,
// 0x07b0b86b41ec7fdfe6c17ee6ccdddce4e47e748e493e542f9a435b0dde022a0d,
// 0x04362e50fcc8be421898d47ace20eab18b0a6efab0e12ade49f2df609fec4209,
// 0x1a779bd9781d3a8354eae5ed74e7fa44fa0e458e45a1407524bddf3b9f2bf2d7]; Autogenerated file - Binary
// Backed
use std::sync::{Arc, OnceLock};

use ark_serialize::CanonicalDeserialize;

use crate::parameters::PoseidonParams;

type Scalar = ark_bn254::Fr;

static MDS_BIN: &[u8] = include_bytes!("params/mds_t4.bin");
static RC_BIN: &[u8] = include_bytes!("params/rc_t4.bin");

pub static POSEIDON_CIRCOM_BN_4_PARAMS: OnceLock<Arc<PoseidonParams<Scalar>>> = OnceLock::new();

pub fn get_t4_params() -> Arc<PoseidonParams<Scalar>> {
    POSEIDON_CIRCOM_BN_4_PARAMS
        .get_or_init(|| {
            let mds = MDS_BIN
                .chunks_exact(32)
                .map(|c| Scalar::deserialize_compressed(c).unwrap())
                .collect::<Vec<_>>()
                .chunks(4)
                .map(|c| c.to_vec())
                .collect();

            let rc = RC_BIN
                .chunks_exact(32)
                .map(|c| Scalar::deserialize_compressed(c).unwrap())
                .collect::<Vec<_>>()
                .chunks(4)
                .map(|c| c.to_vec())
                .collect();

            Arc::new(PoseidonParams::new(4, 5, 8, 56, mds, rc).unwrap())
        })
        .clone()
}
