// Autogenerated file
// KAT:
// Poseidon([0, 1, 2, 3, 4, 5, 6, 7]) =
// [0x1c2f3482dbb140c4ebb9ada49abdbc374a9a85fcfc6533ec2e9df45b4921c318,
// 0x168aa1994e59bb1b957f179b9ad10c260a48342edff90d43cf6c4bce71920802,
// 0x17f1355279be83010f4ffc1d8f6a036475a1d89b3d5c194485de97a7ad37c43c,
// 0x26e89f34c6cd69917b97ac5d2f7ab4f8a095665ddde44e009bf90e000a969dad,
// 0x0b9b2fca1dcc8c30899819b64e29e0d0e8bdaff8c47ea3a38e23915d7bc2555b,
// 0x19cd39910299618d61a1c2e0194e27c59a3f67cd11d62a4cf137a6fa32af3751,
// 0x0b006c56b16c5489f40c563f51a99a2a77da29c53af24c34f0730e6aa2c2a7b6,
// 0x073534f0cedf2b30a870814eee062903ce751e545270c3cbfc5e4732c450ba9c]; Autogenerated file - Binary
// Backed
use std::sync::{Arc, OnceLock};

use ark_serialize::CanonicalDeserialize;

use crate::parameters::PoseidonParams;

type Scalar = ark_bn254::Fr;

static MDS_BIN: &[u8] = include_bytes!("params/mds_t8.bin");
static RC_BIN: &[u8] = include_bytes!("params/rc_t8.bin");

pub static POSEIDON_CIRCOM_BN_8_PARAMS: OnceLock<Arc<PoseidonParams<Scalar>>> = OnceLock::new();

pub fn get_t8_params() -> Arc<PoseidonParams<Scalar>> {
    POSEIDON_CIRCOM_BN_8_PARAMS
        .get_or_init(|| {
            let mds = MDS_BIN
                .chunks_exact(32)
                .map(|c| Scalar::deserialize_compressed(c).unwrap())
                .collect::<Vec<_>>()
                .chunks(8)
                .map(|c| c.to_vec())
                .collect();

            let rc = RC_BIN
                .chunks_exact(32)
                .map(|c| Scalar::deserialize_compressed(c).unwrap())
                .collect::<Vec<_>>()
                .chunks(8)
                .map(|c| c.to_vec())
                .collect();

            Arc::new(PoseidonParams::new(8, 5, 8, 64, mds, rc).unwrap())
        })
        .clone()
}
