// Autogenerated file
// KAT:
// Poseidon([0, 1, 2, 3, 4, 5, 6]) =
// [0x2d1a03850084442813c8ebf094dea47538490a68b05f2239134a4cca2f6302e1,
// 0x09f4d8c9ed66ad207220a0900867c4725780636c62a7c0e62bd77d8ce260543a,
// 0x0a7e491b7b3bea153bb08b76f330bb1019a6eb603ad2da2b30f35cd702c14a18,
// 0x17242bbfab025141fa1ab7efa8641d0e9e67fab33fa47ffef9567973b389feac,
// 0x01faf78a50507f0a6777c18f71690986a5b4a1f93e1ba5051e07aae5da7e0a38,
// 0x2dc78c495bd7c78c7e321bb729b95ed9198d6f54b01b1d9b0e403d35fd014a4e,
// 0x2ac1d41181b675cbbfe7801457f882bfcd0d9994a37a6a105452b48a71f3c810]; Autogenerated file - Binary
// Backed
use std::sync::{Arc, OnceLock};

use ark_serialize::CanonicalDeserialize;

use crate::parameters::PoseidonParams;

type Scalar = ark_bn254::Fr;

static MDS_BIN: &[u8] = include_bytes!("params/mds_t7.bin");
static RC_BIN: &[u8] = include_bytes!("params/rc_t7.bin");

pub static POSEIDON_CIRCOM_BN_7_PARAMS: OnceLock<Arc<PoseidonParams<Scalar>>> = OnceLock::new();

pub fn get_t7_params() -> Arc<PoseidonParams<Scalar>> {
    POSEIDON_CIRCOM_BN_7_PARAMS
        .get_or_init(|| {
            let mds = MDS_BIN
                .chunks_exact(32)
                .map(|c| Scalar::deserialize_compressed(c).unwrap())
                .collect::<Vec<_>>()
                .chunks(7)
                .map(|c| c.to_vec())
                .collect();

            let rc = RC_BIN
                .chunks_exact(32)
                .map(|c| Scalar::deserialize_compressed(c).unwrap())
                .collect::<Vec<_>>()
                .chunks(7)
                .map(|c| c.to_vec())
                .collect();

            Arc::new(PoseidonParams::new(7, 5, 8, 63, mds, rc).unwrap())
        })
        .clone()
}
