[package]
name = "types"
description = "Base Alloy-backed RAILGUN domain types."
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
alloy-primitives = { workspace = true }
bech32 = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }

[lints]
workspace = true
